# Generated by Django 5.2.7 on 2025-10-27 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
    ]
